import tkinter as tk
from tkinter import filedialog, PhotoImage
import tkinter.messagebox as msgbox
from tkinter.messagebox import askquestion
import ctypes
from google import genai
import dotenv
import os
import json
import sys

try: 
    with open('settings.json', 'r') as settings_file:
        settings = json.load(settings_file)
except:
    text_font = 'Arial'
    text_size = '14'
    file_save_on_exit = True
    ai_tools = True

text_font = settings['text_font']
text_size = settings['text_size']
file_save_on_exit = settings['file_save_on_exit']
ai_tools = settings['ai_tools']

if ai_tools: 
    dotenv.load_dotenv()    
    api_key = os.getenv('API_KEY')
    client = genai.Client(api_key=api_key)
    ai_model = 'gemini-2.0-flash'

if sys.platform == 'win32':
    ctypes.windll.shcore.SetProcessDpiAwareness(1)

root = tk.Tk()
root.title('*')
root.geometry('1200x800')
file_name = ''

photo = PhotoImage(file='icon.png') # save an image as icon.png or use original, my icon is 32x32
root.iconphoto(False, photo)

text_widget = tk.Text(root, font=(text_font, text_size))
text_widget.pack(fill='both', expand=True)

def open_file():
    global file_name
    text = text_widget.get('1.0', 'end')
    if text.strip() != '':
        if save_file_qstn(): save_file()
    file_path = filedialog.askopenfilename()
    if file_path:
        text_widget.delete('1.0', 'end')
        with open(file_path, 'r') as file:
            text_widget.insert('1.0', file.read())
            file_name = file_path
    root.title(file_name)

if len(sys.argv) > 1:
    try:
        with open(sys.argv[1], 'r') as file:
            text_widget.insert('1.0', file.read())
            file_name = sys.argv[1]
            root.title(file_name)
    except FileNotFoundError:
        raise RuntimeError('No file found')

def save_as_file():
    global file_name
    file_path = filedialog.asksaveasfilename()
    if file_path:
        with open(file_path, 'w') as file:
            file.write(text_widget.get('1.0', 'end'))
            file_name = file_path
    root.title(file_name)

def save_file():
    global file_name
    text = text_widget.get('1.0', 'end')
    if file_name == '' and text.strip() == '':
        return
    if file_name == '':
        save_as_file()
        return
    with open(file_name, 'w') as file:
        file.write(text)
    root.title(file_name)

def save_file_qstn():
    qstn = msgbox.askquestion("Save", "Save changes?", icon='question')
    return qstn == 'yes'

def save_file_event(event=None):
    save_file()
    return 'break'

root.bind('<Control-s>', save_file_event)


def new_file():
    global file_name
    text = text_widget.get('1.0', 'end-1c').strip()
    if text != '' or file_name != '':
        if save_file_qstn(): save_file()
    file_name = ''
    text_widget.delete('1.0', 'end')
    root.title('*')

def cut():
    text_widget.event_generate('<<Cut>>')
def copy():
    text_widget.event_generate('<<Copy>>')
def paste():
    text_widget.event_generate('<<Paste>>')
def select_all():
    text_widget.tag_add('sel', '1.0', 'end')

def googleAIspellcheck():
    global ai_model
    response = client.models.generate_content(
        model=ai_model,
        contents='Spellcheck this, return only the text in the same format: ' + text_widget.get(1.0, 'end'),
    )
    text_widget.delete('1.0', 'end')
    text_widget.insert('end', response.text)
    msgbox.showinfo('AI Info', f'Spelling checked by {ai_model}, check for errors.')

def googleAIgenerate():
    global ai_model
    response = client.models.generate_content(
        model=ai_model,
        contents='Answer without adding any filler text' + text_widget.get(1.0, 'end'),
    )
    text_widget.delete('1.0', 'end')
    text_widget.insert('end', response.text)
    msgbox.showinfo('AI Info', f'Generated by {ai_model}, check for errors.')

def quit_app():
    text = text_widget.get('1.0', 'end').strip()
    if file_save_on_exit and text != '':
        if save_file_qstn(): save_file()
    root.quit()
    root.destroy()


menu_bar = tk.Menu(root)

file_menu = tk.Menu(menu_bar, tearoff=0)
file_menu.add_command(label='Open', command=open_file)
file_menu.add_command(label='Save as', command=save_as_file)
file_menu.add_command(label='Save', command=save_file)
file_menu.add_separator()
file_menu.add_command(label='New', command=new_file)
file_menu.add_separator()
file_menu.add_command(label='Exit', command=quit_app)
menu_bar.add_cascade(label='File', menu=file_menu)


edit_menu = tk.Menu(menu_bar, tearoff=0)
edit_menu.add_command(label='Cut', command=cut)
edit_menu.add_command(label='Copy', command=copy)
edit_menu.add_command(label='Paste', command=paste)
edit_menu.add_separator()
edit_menu.add_command(label='Select All', command=select_all)
menu_bar.add_cascade(label='Edit', menu=edit_menu)
if ai_tools:
    ai_menu = tk.Menu(menu_bar, tearoff=0)
    ai_menu.add_command(label='Spellcheck', command=googleAIspellcheck)
    ai_menu.add_command(label='Generate', command=googleAIgenerate)
    menu_bar.add_cascade(label='AI', menu=ai_menu)

root.config(menu=menu_bar)

root.mainloop()

